name: Validate
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: install
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.20.0
          go install github.com/golangci/golangci-lint/cmd/golangci-lint
          golangci-lint --version

      - name: lint
        run: |
          golangci-lint run --disable wsl ./...
          cd v2
          golangci-lint run --disable wsl ./...

      - name: test
        run: |
          go clean
          go get ./...
          go test ./... --short -count=1

          cd v2
          go clean
          go get ./...
          go test ./... --short -count=1
