name: Validate
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: install
        run: |
          - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.20.0
          - go install github.com/golangci/golangci-lint/cmd/golangci-lint
          - golangci-lint --version
      - name: lint
        run: |
          - golangci-lint run --disable wsl ./...
          - cd v2
          - golangci-lint run --disable wsl ./...
      - name: test
        run: |
          - go clean
          - go test ./... --short -count=1

          - go clean
          - go test ./... --short -count=1
